apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.backend.monitor.name }}
  namespace: monitoring
  labels:
    app: {{ .Values.backend.appName }}
    release: {{ .Values.release.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.backend.appName }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
